### ISSUE TITLE
Strange console behavior on linux guest installation

### ISSUE THREAD

**Issue by icsy7867** [pr1ntf/iohyve#162]
I have not found very much on the matter.  So I thought i would post it.  I have tried this on my local Freenas console, via putty (SSH), and SSH'ing from an Ubuntu and FreeBSD VM.

Now I actuallty have an ubuntu guest setup and running, which I somehow got working by hitting the right keys I suppose.  I believe IOHYVE/BHYVE are working as intended, I just don't think I can get the ssh window to display the information correctly.  I have even tried changing the remote character set options in putty, and how putty draws lines.

Since I am only moderately computer savvy with BSD/Linux I decided to screenshot my entire process so I do not sound like a complete moron when trying to explain what I am seeing.  Sorry for all the picture.  This very well may be be user error. 

Here is a basic setup of how I create the guest:

> sudo iohyve create ubuntuserver 15G
> sudo iohyve set ubuntuserver loader=grub-bhyve
> sudo iohyve set ubuntuserver os=debian
> sudo iohyve set ubuntuserver ram=1024M
> sudo iohyve set ubuntuserver cpu=2
> sudo iohyve set ubuntuserver con=nmdm1
> sudo iohvye install ubuntuserver ubuntuISO.iso

The console shows what you would expect:
![All is well](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/1_zpsgnmedlhr.png)

After this, I should simply hit "**Enter**"
![uh oh](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/2_zpsmsracds9.png)

I have a sneaking suspicious that my input keys are not being sent correctly.  For example... typing in "Clear" repeatedly to the grub> line yields:

```
grub> clear
error: can't find command `lel'.
grub> clear
error: can't find command `cllrelar'.
grub> clear
error: can't find command `cleala'.
grub> clear
error: can't find command `cecrl'.
```

You can kind of see bits of the text being sent correctly

So I wait a little while and mash enter a few times...
![garbage](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/3%20-%20pressing%20enter%20a%20few%20times_zpsfhiqnce5.png)

And continue to do so, getting random garbage until:
![Normalcy](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/4%20-%20Normalacy_zpsb4nhfmwo.png)

WHEW! I thought I was in trouble there for a minute.  So now "Space" selects...
![huh...](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/5%20-%20spacebar_zps8cvrurnv.png)

Well that was weird...Maybe a few more spaces will do it...Or maybe enter?
![spaces](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/6%20-%20enter%20a%20few%20times_zpsvpgonoub.png)

Lets try a tab...
![tab](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/7%20-%20tab_zpslnb2k5qu.png)

Okay at this point... I am just mashing keys.  Here is me holding down the "Down Arrow".  Now I have found an interesting behavior after this (Which is why I am doing it so bare with me...)
![down arrow](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/8%20-%20down_zpsjdwgpv1i.png)

Now at some point in spamming buttons, the window decides to redraw itself it seems...
![uh oh](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/9%20-%20eventually_zpscyhqtoc6.png)

But using the "Space" as the window suggests just tosses up the same type of weirdness...
![uh oh](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/10%20-weirdness_zpsndzm2c7i.png)

Currently I am having much better results selecting items using "Tab + Right Click" which is weird... I can actually use tab to select, which messes up the window as seen about, and then "**Right Click**" is causing the terminal to mostly redraw the window.  So getting to the name your machine section of the ubuntu install, I can actually type in something like "UbuntuServer" but hitting "Tab + Right Click" yields:
![uh oh](http://i204.photobucket.com/albums/bb318/ICANSEE7687/Mobile%20Uploads/12%20-%20right%20click_zpsgirdzzzl.png)

Which sort of shows all the crap that gets hit when the "**TAB**" button is pressed.

**Comment by EpiJunkie** [comment]
> I have a sneaking suspicious that my input keys are not being sent correctly. For example... typing in "Clear" repeatedly to the grub> line yields:
> 
> ```
> grub> clear
> error: can't find command `lel'.
> grub> clear
> error: can't find command `cllrelar'.
> grub> clear
> error: can't find command `cleala'.
> grub> clear
> error: can't find command `cecrl'.
> ```

When this happens, it is due to more than one guest connected to the same `nmdm` session. Basically, the `cu` console sends some of the keyboard input to one guest and some to the other. Which is why you are getting the `error: can't find command` messages above.

This can happen if you have changed the console properties for the guests or perhaps a few guests have been deleted and new ones created. I had this happen to me one time, I unfortunately do not remember how it happen. Maybe you can shed some light on what you did? Can you reproduce it?

I recommend stopping all the guests and then running `iohyve info -v` and check that all the console ports are unique. If they are then all unique then start the guests back up. This should resolve the problem. The rest of the issues are very likely related to this.

Please report back and let us know.

**Comment by pr1ntf** [comment]
@EpiJunkie hit the nail on the head here. It looks like you are connected to two guests. 

I'd also like to note that when you are having console issues, I have included the `iohyve conreset` function that kills off all `cu` sessions on the host. This greatly helps when you change the `con` property and might still have a console open elsewhere.

**Comment by icsy7867** [comment]
Well I do have other guests but none of them are running.  The screenshots taken above were also after a full reboot and I do not have any VM's set to run on boot. (Where ubserv is my current VM I am messing with):

```
freebsd103    NO    NO       NO       Tue Apr 12 10:56:07 EDT 2016
ubserv        YES   YES      NO       Tue May  3 16:29:44 EDT 2016
ubuntuserver  NO    NO       NO       Wed Apr 13 16:12:16 EDT 2016
```

`iohyve info -v`
Gives me an "invalid flag".  Viewing the help the only flag I can see is -d, which does not appear to have console information.

iohyve conreset returns:
No Matching processes were found.

**Comment by EpiJunkie** [comment]
My apologizes, the `-v` flag for `iohyve info` is in HEAD and not yet in a release. `iohyve conlist` will work then. Are there other bhyve managers running on your system or perhaps other applications that would utilize the same `/dev/nmdm` device?

Also could you post the output of: `ls -lah /dev/nmdm*`?

**Comment by icsy7867** [comment]
I really appreciate yalls quick responses to help me out here!  There should not be any other BHYVE managers.

```
Guest         Console
freebsd103    nmdm0
ubserv        nmdm2
ubuntuserver  nmdm1
```

```
ls -lah /dev/nmdm*
crw-------  1 root  wheel  0x13a May  5 10:29 /dev/nmdm0A
crw-------  1 root  wheel  0x13b May  5 10:29 /dev/nmdm0B
crw-------  1 root  wheel  0x132 May  5 10:49 /dev/nmdm2A
crw-------  1 root  wheel  0x133 May  4 17:38 /dev/nmdm2B
```

I have sense been playing with setting the con=nmdn# a good bit so i'm not exactly sure where I am out.  But I noticed that it was possible that I had two guests running on nmdm1 so I changed ubserv to nmdm2.  When this also showed identical behavior I also tried setting it to nmdm3 and trying again.

**Comment by EpiJunkie** [comment]
Changing the console property while the guest is running will cause some(/this) interesting behavior. There are not any internal checks for this. You should at least bring the guest to a full stop ("NO" displayed for "VMM" and "Running" in `iohyve list`) and then start the guest again.

**Comment by icsy7867** [comment]
Of course, im not sure why there was still a VMM loaded.  But after running IOHYVE Destroy and ensure the vm was not running and restarting the installation, I saw the same behavior.

**Comment by EpiJunkie** [comment]
So do all of that again, then run `iohyve conreset`, and then start the guest(s).

**Comment by icsy7867** [comment]
```
Guest         VMM?  Running  rcboot?  Description
freebsd103    NO    NO       NO       Tue Apr 12 10:56:07 EDT 2016
ubserv        NO    NO       NO       Tue May  3 16:29:44 EDT 2016
ubuntuserver  NO    NO       NO       Wed Apr 13 16:12:16 EDT 2016

% sudo iohyve conlist
Guest         Console
freebsd103    nmdm0
ubserv        nmdm3
ubuntuserver  nmdm1

% sudo iohyve conreset
No matching processes were found
```

I then tried to reinstall with the same behavior.  I can actually stumble my way through a lot of the setup.  For instance, the defaults are almost always fine, and I can mash Enter until the next screen (Usually takes a few presses).  Its the creating a password for the default user that gets tricky since the keys do not see to input correctly.

Also, it is probably worth noting, that if/when the installation finishes, and I SSH into the guest, the terminal displays and inputs/outputs just fine.  This only happens during installation.

**Comment by pr1ntf** [comment]
You may have a random `grub-bhyve` process floating around. It should show in `top` or running `ps -aux | grep grub-bhyve`. 

Because iohyve attaches the serial console to both the `grub-bhyve`/`bhyveload` process and the `bhyve` process, you may run into some issues.

**Comment by icsy7867** [comment]
Thanks for the response!

I get a 3-4 processes running on nmdm3A and nmdm2A.  Running IOHYVE list everything is set to "NO".

If I manually kill these processes, and then run iohyve list, the guest that this issue is about all of a sudden gets VMM? set to "YES".

And after I redo a sudo iohyve destroy ubserv the processes appear back after running:
ps -aux | grep grub-bhyve

**Comment by pr1ntf** [comment]
It appears you have fallen victim to the dreaded `grub-bhyve` boot loop. It comes in many forms, and acts quite like the mythical creature [Hydra](https://en.wikipedia.org/wiki/Lernaean_Hydra); every time you chop off one of it's heads, another appears. 

There is a tool of the dark side, `iohyve forcekill $guestname`. It's a tool of the darkside because it kills off any process with the name `$guestname` in it. This could have adverse effects if wielded unwisely. It's also prudent to run `iohyve conreset` after running `iohyve forcekill $guestname`. [Here's](https://github.com/pr1ntf/iohyve/blob/92ddae038b30ba6061b87374cefee3ade3029280/lib/ioh-guest#L534) the code it runs. 

This is due to the way the subshell is spawned. Basically, you need to kill off the `grub-bhyve` _and_ the `iohyve` process.

**Comment by EpiJunkie** [comment]
@pr1ntf I totally forgot about `grub-bhyve` being attached to the same `nmdm` console. That and the regrowing `grub-bhyve` lizard tail explain the problem here.

**Comment by icsy7867** [comment]
Interesting...

For the initial ubuntu installation window (After running your above commands), everything actually appears to be normal.  And once I hit the second window things go screwy again.

But I definitely see what you all are saying.  It seems to be sharing a console with grub-bhyve.  This also explains that when I am trying to enter a username/password (It is more visible with the password) part of the text goes to the "grub> " portion and the other portions gets sent to the ubserv console.

For example when I type a password I see something like

Pas*_o_d for the password.  And upon hitting "enter" that pesky little grub> thing will come back saying something like
grub> Pasod unknown.

So interesting enough, if I start the VM BEFORE the install command, it takes me into grub, where all my keystrokes, arrow keys, and enter functions completely normal

**Comment by pr1ntf** [comment]
Do you get the orphan `grub-bhyve` processes every time you boot a guest? If you have run `iohyve forcekill $guestname` for all your `grub-bhyve` guests and `top` or `ps -aux | grep grub-bhyve` return nothing, you shouldn't see any issues after starting guests.

**Comment by icsy7867** [comment]
Sorry for the delayed response, I was out camping and my SSH abilities was slightly limited...

Here are my VM's

```
Guest         VMM?  Running  rcboot?  Description
freebsd103    NO    NO       NO       Tue Apr 12 10:56:07 EDT 2016
ubserv        NO    NO       NO       Tue May  3 16:29:44 EDT 2016
ubuntuserver  NO    NO       NO       Wed Apr 13 16:12:16 EDT 2016
```

```
sudo iohyve forcekill ubserv
VM:ioh-ubserv is not created.
sudo iohyve forcekill ubuntuserver
VM:ioh-ubserv is not created.
sudo iohyve forcekill freebsd103
VM:ioh-ubserv is not created.
```

And after running the ps -a command, the only grub-bhyve process is the grep process.

```
 ps -a | grep grub-bhyve
58913  0  S+   0:00.00 grep grub-bhyve
```

And now it seems to be working flawlessly!  Although I did this before and these same things came back with nothing running.  I am gonna try to do some testing, but I am ecstatic that this is working so well!  Thank you guys for your time!

**Comment by pr1ntf** [comment]
I'm glad you got sorted out. Let us know if you run into any further issues. :sunglasses:
